#!/usr/bin/env python3

from subprocess import run, Popen, PIPE
from sys import argv
from os import path
from urllib.parse import quote


add_cmd = 'ipfs add --cid-version=1 --nocopy --raw-leaves --fscache --wrap-with-directory --recursive'


urls = [
    'http://127.0.0.1:8080/ipfs',
    'https://ipfs.io/ipfs',
]

if len(argv) == 1:
    print(
        '''USAGE:
   ipfs-share file.ext
   ipfs-share path/to/dir
   ipfs-share http://path.to/file.ext
\b'''
    )


def run_cmd(cmd):
    p = Popen(cmd, shell=True, text=True, stdout=PIPE)
    return p.communicate(timeout=None)


if len(argv) > 1:
    file_name = path.basename(argv[1])
    file_name_quote = quote(file_name)

    out, err = run_cmd(f"{add_cmd} '{argv[1]}'")

    out_split = out.split()
    for i, v in enumerate(urls):
        urls[i] = f'{v}/{out_split[-1]}/{file_name_quote}'

    print(out)
    print(f'http://{out_split[-1]}.ipfs.localhost:8080/{file_name_quote}\n')
    print('\n\n'.join(urls))

    run(f"wl-copy '{urls[-1]}'", shell=True)
